/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AggregatorV2V3Interface } from "./AggregatorV2V3Interface";
export type { MockAggregatorV2V3 } from "./MockAggregatorV2V3";
