/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AggregatorV2V3Interface__factory } from "./AggregatorV2V3Interface__factory";
export { MockAggregatorV2V3__factory } from "./MockAggregatorV2V3__factory";
